### ISSUE TITLE
pretrained models for COVID-19 CT segmentation

### ISSUE THREAD

**Issue by JunMa11** [black0017/MedicalZooPytorch#2]
Hi @black0017 ,

Thanks for your great work.

I notice that you are also working on pre-trained models on public datasets.

[Here](https://github.com/JunMa11/COVID-19-CT-Seg-Benchmark) is a benchmark for lung and infection segmentation in COVID-19 CT scans. 

Are you interested in including this COVID-19 segmentation dataset for pre-trained models?

Best regards,
Jun

**Comment by black0017** [comment]
Hello and thanks for the comment.

We uploaded a dataloader for covid segmentation dataset (taks1 in your git) and a test file to run with most of our architectures. Feel free to share a link in your coniv benchmark segm repo.

We will provide update on this when we start to realese pre-trained models. It will take some time, since we have a lot of experiments!!!

Before we want to do a massive cleanup on the repo and clarify the API so that people can use it smoothly.

Thanks.
